services:
  
  golang-app:
    build: .
    restart: always
    container_name: api
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=centurion.key-city.com
      - LETSENCRYPT_HOST=centurion.key-city.com
      - LETSENCRYPT_MAIL=luis@key-city.com



